// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnsrshciphzhoqkhjcxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imduc3JzaGNpcGh6aG9xa2hqY3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5MTU0NTcsImV4cCI6MjA1NjQ5MTQ1N30.-EjcYPYGIKENcQBE0N3kSzw9HlNoSQc-6qljmOW-saQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);